### ISSUE TITLE
[CHORE] - Create app structure and add dependencies

### ISSUE THREAD

**Issue by dave-ok** [hngi/fury-backend-node#12]
**Brief description of tasks and objectives**
Scaffold application creating the initial app structure and installing dependencies

**Acceptance criteria to qualify for completion**
- [ ] 1. Create application directories
- [ ] 2. Install dependencies

**Comment by fisayo-DMG** [comment]
I am interested in working on this feature but I'll need more information regarding the functionality of what we are building.
