### ISSUE TITLE
[CHORE]: Update README.md file

### ISSUE THREAD

**Issue by obsessedyouth** [hngi/fury-backend-node#5]
The current readme has no information regarding the project.
An updated README.md with a title, brief description, relevant information and steps on how to setup the project locally or otherwise and so on.

**Comment by simply-alliv** [comment]
Hey, please don't remove the questions from the templates. As I have [explained](https://hngi7.slack.com/archives/G0150HBKZ4J/p1591648594052900?thread_ts=1591643319.030600&cid=G0150HBKZ4J) in our thread.
